### ISSUE TITLE
Share a provider

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/fsd-spike#35]
As a user 
I want to be able to share this contact
Because they offer a good service

A / C
 - [x] Implement AddThis (Node Module)
 - [x] Should be able to share with Facebook
 - [x] Should be able to share with Facebook Messenger
 - [x] Should be able to email the service provider details

**Comment by dlouise64** [comment]
closes #34

**Comment by Br3nda** [comment]
Share a provider is not implemented -- but MSD would rather have the feature in #56 instead. So this can stay closed.
